apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-production
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prakasa1904/wpe-lite:05032020
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio