# ================ INFO ================
# Basic Kubernetes
# ================ INFO ================
ns :=istio-system

get-contexts:
	@kubectl config get-contexts

get-namespaces:
	@kubectl get namespaces

get-services:
	@kubectl get services --namespace $(ns)

get-deployments:
	@kubectl get deployments --namespace $(ns)

get-pods:
	@kubectl get pods --namespace $(ns)

